# Generated by Django 5.2.17 on 2026-09-27 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, default='Custom', max_length=150)),
                ('source_url', models.URLField(blank=True)),
                ('version', models.CharField(blank=True, default='1.0', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'sheets',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SheetSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sheets.sheet')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('sheet', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SheetProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_removed', models.BooleanField(default=False, help_text='Keeps a slot without deleting the problem.')),
                ('notes', models.TextField(blank=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_problems', to='problems.problem')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='sheets.sheetsection')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('section', 'problem')},
            },
        ),
    ]
