# Generated by Django 5.2.17 on 2026-09-27 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('attempted', 'Attempted'), ('solved', 'Solved')], default='not_started', max_length=15)),
                ('accepted', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('first_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='execution.language')),
                ('last_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.submission')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='progress_pr_user_id_9c911f_idx'), models.Index(fields=['-completed_at'], name='progress_pr_complet_891fae_idx')],
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
