# Generated by Django 5.2.17 on 2026-09-27 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('run', 'Run (sample/custom cases)'), ('submit', 'Submit (all cases)')], default='submit', max_length=8)),
                ('verdict', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('compilation_error', 'Compilation Error'), ('runtime_error', 'Runtime Error'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('empty_submission', 'Empty Submission'), ('internal_error', 'Internal Error')], default='internal_error', max_length=32)),
                ('test_cases_passed', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('execution_time', models.FloatField(default=0.0, help_text='Total seconds.')),
                ('max_execution_time', models.FloatField(default=0.0, help_text='Slowest single test case, seconds.')),
                ('memory_used', models.BigIntegerField(default=0, help_text='Peak RSS in bytes, best effort.')),
                ('error_message', models.TextField(blank=True)),
                ('compile_output', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('estimated_time_complexity', models.CharField(blank=True, max_length=40)),
                ('estimated_space_complexity', models.CharField(blank=True, max_length=40)),
                ('complexity_confidence', models.CharField(blank=True, max_length=10)),
                ('complexity_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='execution.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('input_data', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('actual_output', models.TextField(blank=True)),
                ('verdict', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('compilation_error', 'Compilation Error'), ('runtime_error', 'Runtime Error'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('memory_limit_exceeded', 'Memory Limit Exceeded'), ('empty_submission', 'Empty Submission'), ('internal_error', 'Internal Error')], max_length=32)),
                ('execution_time', models.FloatField(default=0.0)),
                ('memory_used', models.BigIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('is_sample', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='submissions.submission')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='problems.testcase')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', '-submitted_at'], name='submissions_user_id_43efd8_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', '-submitted_at'], name='submissions_problem_d24719_idx'),
        ),
    ]
