# Generated by Django 5.2.17 on 2026-09-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('file_extension', models.CharField(default='.txt', max_length=12)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('runner', models.CharField(default='script', max_length=40)),
                ('compile_command', models.TextField(blank=True, help_text='Leave empty for interpreted languages. e.g. g++ {file} -O2 -o {out}')),
                ('execution_command', models.TextField(blank=True, help_text='e.g. {python} {file_name}')),
                ('run_env', models.JSONField(blank=True, default=dict)),
                ('time_limit', models.FloatField(default=5.0, help_text='Wall clock seconds per test case.')),
                ('memory_limit_mb', models.PositiveIntegerField(default=512, help_text='Address space / heap cap in megabytes.')),
                ('enforce_address_space_limit', models.BooleanField(default=True)),
                ('compile_timeout', models.FloatField(default=30.0)),
                ('monaco_language', models.CharField(default='plaintext', help_text='Monaco language id.', max_length=30)),
                ('editor_mode', models.CharField(blank=True, help_text='Monaco editor mode override.', max_length=30)),
                ('comment_prefix', models.CharField(default='#', max_length=4)),
                ('docker_image', models.CharField(blank=True, help_text='Optional sandbox image.', max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
