# Generated by Django 5.2.17 on 2026-09-27 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'domains',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Supports basic HTML. Markdown is not rendered.')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('constraints', models.TextField(blank=True, help_text='One constraint per line.')),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True, help_text='Markdown/plain examples.')),
                ('hints', models.TextField(blank=True, help_text='One hint per line.')),
                ('explanation', models.TextField(blank=True)),
                ('execution_mode', models.CharField(choices=[('function', 'Function signature (harness calls your solution)'), ('stdin', 'Read from stdin, write to stdout')], default='function', help_text="'function': test case input is a JSON array of arguments and the harness calls the solution function. 'stdin': the raw text is piped to stdin and stdout is compared.", max_length=12)),
                ('function_name', models.CharField(blank=True, default='solution', max_length=80)),
                ('param_spec', models.JSONField(blank=True, default=list, help_text='Ordered parameter type specs for compiled languages, e.g. ["int[]", "int"]. Types: int, long, double, bool, string, int[], long[], double[], string[], int[][], ListNode, TreeNode.')),
                ('return_spec', models.CharField(blank=True, help_text='Return type spec, e.g. int, int[], string, ListNode, void.', max_length=40)),
                ('time_limit', models.FloatField(blank=True, null=True)),
                ('memory_limit_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_time_complexity', models.CharField(blank=True, max_length=40)),
                ('expected_space_complexity', models.CharField(blank=True, max_length=40)),
                ('solution_notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, default='Custom', max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text="e.g. LeetCode id '1'.", max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(blank=True, related_name='problems', to='problems.domain')),
                ('primary_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='problems.domain')),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('input_data', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('is_sample', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('comparison', models.CharField(choices=[('exact', 'Exact (order matters)'), ('unordered', 'Unordered (group/order does not matter)')], default='exact', max_length=16)),
                ('expected_time_ms', models.FloatField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10)),
                ('editor', models.CharField(default='monaco', max_length=20)),
                ('editor_theme', models.CharField(default='vs-dark', max_length=30)),
                ('editor_font_size', models.PositiveSmallIntegerField(default=14)),
                ('show_editor_intro', models.BooleanField(default=True, help_text='Show the editor guide panel on the problem page.')),
                ('autosave', models.BooleanField(default=True)),
                ('autosave_delay_ms', models.PositiveIntegerField(default=1200)),
                ('execution_timeout', models.FloatField(default=5.0, help_text='Default per-test-case time limit in seconds.')),
                ('keyboard_shortcuts', models.BooleanField(default=True)),
                ('run_shortcut', models.CharField(default='Ctrl+Enter', max_length=20)),
                ('submit_shortcut', models.CharField(default='Ctrl+Shift+Enter', max_length=20)),
                ('save_shortcut', models.CharField(default='Ctrl+S', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='execution.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemStarterCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_code', models.TextField()),
                ('solution_reference', models.TextField(blank=True, help_text='Optional reference solution used for self-checks.')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_codes', to='execution.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_codes', to='problems.problem')),
            ],
            options={
                'ordering': ['language__order', 'language__name'],
                'unique_together': {('problem', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SavedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_codes', to='execution.language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_codes', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'problem', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['difficulty'], name='problems_pr_difficu_d3b056_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['-updated_at'], name='problems_pr_updated_62f115_idx'),
        ),
    ]
