# Generated by Django 5.2.17 on 2026-09-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='checker',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
