"""Index-level structure of the bundled DSA sheets.

These files list the well known *titles* of the questions in each popular
sheet, grouped into their published step/topic structure, with a difficulty and
topic classification.  The statements and test cases live in
``tools/problem_library.py``; anything not in that library is imported as a
title-only entry that you can fill in later from the admin panel or with your
own data file.

Running ``python tools/build_sheet_data.py`` regenerates ``data/sheets/*.json``
from this file plus the problem library.
"""

# Each item: (title, difficulty, [domains])

STRIVER_A2Z = [
    ("Step 1 - Learn the Basics", [
        ("1.1 - Time Complexity", "Easy", ["Math"]),
        ("1.2 - Space Complexity", "Easy", ["Math"]),
        ("1.3 - Input / Output", "Easy", ["Basics"]),
        ("1.4 - Total Decimals", "Easy", ["Math"]),
        ("1.5 - nCr", "Medium", ["Math", "Recursion"]),
        ("1.6 - nPr", "Medium", ["Math", "Recursion"]),
        ("1.7 - Factorials", "Easy", ["Math"]),
        ("1.8 - Min and Max", "Easy", ["Array"]),
        ("1.9 - Modular Exponentiation", "Medium", ["Math", "Bit Manipulation"]),
        ("1.10 - Modular Inverse", "Hard", ["Math"]),
        ("1.11 - Number of Digits", "Easy", ["Math"]),
        ("1.12 - Increasing Decreasing Digits", "Easy", ["Math"]),
        ("1.13 - Spell Number", "Medium", ["Math", "String"]),
        ("1.14 - Optimal Numbers", "Medium", ["Math", "Greedy"]),
        ("1.15 - Add Digits", "Easy", ["Math"]),
        ("1.16 - Count Digits", "Easy", ["Math"]),
        ("1.17 - Divide and Conquer Basics", "Medium", ["Recursion"]),
        ("1.18 - Kth Digit", "Easy", ["Math"]),
        ("1.19 - Sorting Elements", "Easy", ["Sorting"]),
        ("1.20 - Building Numbers", "Easy", ["Math", "String"]),
        ("1.21 - Reverse a Number", "Easy", ["Math"]),
        ("1.22 - Print the Number of Digits", "Easy", ["Math"]),
    ]),
    ("Step 2 - Sorting", [
        ("2.1 - Bubble Sort", "Easy", ["Sorting"]),
        ("2.2 - Selection Sort", "Easy", ["Sorting"]),
        ("2.3 - Insertion Sort", "Easy", ["Sorting"]),
        ("2.4 - Quick Sort", "Medium", ["Sorting", "Recursion"]),
        ("2.5 - Merge Sort", "Medium", ["Sorting", "Recursion"]),
    ]),
    ("Step 3 - Arrays", [
        ("3.1 - Two Sum", "Easy", ["Array", "Hashing"]),
        ("3.2 - Second Largest Element", "Easy", ["Array"]),
        ("3.3 - Largest Element", "Easy", ["Array"]),
        ("3.4 - Smallest Number", "Easy", ["Array"]),
        ("3.5 - Check if Array is Sorted", "Easy", ["Array"]),
        ("3.6 - Count Elements Less Than or Equal to K", "Medium", ["Array", "Sorting"]),
        ("3.7 - Count Small and Large Elements", "Easy", ["Array"]),
        ("3.8 - Maximum and Minimum Product", "Medium", ["Array", "Greedy"]),
        ("3.9 - Toggle Switches", "Medium", ["Array", "Math"]),
        ("3.10 - Prefix Sum", "Easy", ["Array"]),
        ("3.11 - Rotate Array", "Medium", ["Array", "Two Pointer"]),
        ("3.12 - Search in Rotated Sorted Array", "Medium", ["Binary Search", "Array"]),
        ("3.13 - Search in Rotated Sorted Array (Approach 2)", "Medium", ["Binary Search", "Array"]),
        ("3.14 - Find Position of an Element in a Sorted Array of Infinite Numbers", "Medium", ["Binary Search"]),
        ("3.15 - Find the Smallest Difference Array", "Medium", ["Array", "Sorting"]),
        ("3.16 - Count Elements With Frequency Less Than k", "Medium", ["Array", "Hashing"]),
        ("3.17 - Sort an Array of 0s, 1s and 2s", "Medium", ["Array", "Two Pointer"]),
        ("3.18 - Rabin-Karp Algorithm", "Hard", ["String", "Hashing"]),
        ("3.19 - KMP Algorithm", "Hard", ["String"]),
        ("3.20 - Z Algorithm", "Hard", ["String"]),
        ("3.21 - Binary Search on a Sorted Array", "Easy", ["Binary Search", "Array"]),
        ("3.22 - Find a Peak Element", "Medium", ["Binary Search", "Array"]),
        ("3.23 - Number of Smaller Elements", "Hard", ["Binary Search", "Array"]),
        ("3.24 - K-th Element of Two Sorted Arrays", "Medium", ["Binary Search", "Array"]),
        ("3.25 - K-th Smallest Element", "Medium", ["Heap", "Array"]),
        ("3.26 - Aggressive Cows", "Hard", ["Binary Search", "Array"]),
        ("3.27 - Book Allocation Problem", "Hard", ["Binary Search", "Array"]),
        ("3.28 - Painter's Partition Problem", "Hard", ["Binary Search", "Array"]),
    ]),
    ("Step 4 - Strings", [
        ("4.1 - Remove Consecutive Characters", "Easy", ["String"]),
        ("4.2 - Is Palindrome", "Easy", ["String", "Two Pointer"]),
        ("4.3 - Is Palindrome (Efficient)", "Easy", ["String"]),
        ("4.4 - Compare Two Strings", "Easy", ["String"]),
        ("4.5 - Palindrome Number", "Easy", ["Math", "String"]),
        ("4.6 - Longest Palindromic Substring", "Medium", ["String", "Dynamic Programming"]),
        ("4.7 - Valid Palindrome", "Easy", ["String", "Two Pointer"]),
        ("4.8 - Valid Anagram", "Easy", ["String", "Hashing"]),
        ("4.9 - Valid Parenthesis", "Easy", ["String", "Stack"]),
        ("4.10 - Valid IP Address", "Medium", ["String"]),
        ("4.11 - Find All Anagrams in a String", "Medium", ["String", "Sliding Window", "Hashing"]),
        ("4.12 - String Matching", "Hard", ["String", "KMP"]),
        ("4.13 - Tries", "Medium", ["Trie", "String"]),
        ("4.14 - Minimum Number of Flips to Make the Binary String Alternating", "Medium", ["String", "Sliding Window"]),
        ("4.15 - Rearrange String", "Medium", ["String", "Heap", "Greedy"]),
        ("4.16 - Simplify String", "Medium", ["Stack", "String"]),
        ("4.17 - Maximum Nesting Depth of the Parentheses", "Medium", ["Stack", "String"]),
        ("4.18 - Add to Linked-List", "Medium", ["Linked List", "String"]),
        ("4.19 - Reverse Words in a String", "Medium", ["String"]),
    ]),
    ("Step 5 - Linked List", [
        ("5.1 - Introduction to Linked List", "Easy", ["Linked List"]),
        ("5.2 - Insertion", "Easy", ["Linked List"]),
        ("5.3 - Deletion", "Easy", ["Linked List"]),
        ("5.4 - Reverse a Linked List", "Easy", ["Linked List"]),
        ("5.5 - Middle of the Linked List", "Easy", ["Linked List", "Two Pointer"]),
        ("5.6 - Check if a Linked List is a Palindrome", "Medium", ["Linked List", "Stack"]),
        ("5.7 - Add Two Numbers", "Medium", ["Linked List", "Math"]),
        ("5.8 - Maximum Sum of Two Numbers in a Linked List", "Medium", ["Linked List", "Two Pointer"]),
        ("5.9 - Remove N-th Node From the End of the Linked List", "Medium", ["Linked List", "Two Pointer"]),
        ("5.10 - Delete Node in a Linked List", "Easy", ["Linked List"]),
        ("5.11 - Reverse Nodes in a Group of Given Size", "Hard", ["Linked List"]),
        ("5.12 - Flatten a Linked List", "Hard", ["Linked List"]),
        ("5.13 - Merge Two Sorted Linked Lists", "Medium", ["Linked List"]),
        ("5.14 - Sort a Linked List", "Hard", ["Linked List", "Merge Sort"]),
        ("5.15 - Design Linked List", "Medium", ["Linked List", "Design"]),
    ]),
    ("Step 6 - Recursion (Backtracking)", [
        ("6.1 - Recursive Backtracking", "Easy", ["Backtracking", "Recursion"]),
        ("6.2 - N Queens", "Hard", ["Backtracking", "Matrix"]),
        ("6.3 - N Queens II", "Hard", ["Backtracking", "Matrix"]),
        ("6.4 - Sudoku Solver", "Hard", ["Backtracking", "Matrix"]),
        ("6.5 - Word Search", "Medium", ["Backtracking", "Matrix"]),
        ("6.6 - Permutations", "Medium", ["Backtracking", "Recursion"]),
        ("6.7 - Permutations II", "Hard", ["Backtracking", "Recursion"]),
        ("6.8 - Combination Sum", "Medium", ["Backtracking", "Recursion"]),
        ("6.9 - Combination Sum II", "Medium", ["Backtracking", "Recursion"]),
        ("6.10 - Subset Sum", "Medium", ["Backtracking", "Recursion"]),
        ("6.11 - Palindrome Partitioning", "Hard", ["Backtracking", "Dynamic Programming", "String"]),
    ]),
    ("Step 7 - Trees", [
        ("7.1 - Introduction to Trees", "Easy", ["Tree"]),
        ("7.2 - Traversals", "Easy", ["Tree"]),
        ("7.3 - Height of a Tree", "Easy", ["Tree"]),
        ("7.4 - Maximum Depth of Binary Tree", "Easy", ["Tree"]),
        ("7.5 - Count Nodes in a Binary Tree", "Easy", ["Tree"]),
        ("7.6 - Sum of Nodes", "Easy", ["Tree"]),
        ("7.7 - Check if a Binary Tree is Identical", "Easy", ["Tree"]),
        ("7.8 - Inorder Traversal of a Binary Tree", "Easy", ["Tree"]),
        ("7.9 - Preorder Traversal", "Easy", ["Tree"]),
        ("7.10 - Postorder Traversal", "Easy", ["Tree"]),
        ("7.11 - Level Order Traversal", "Medium", ["Tree", "Queue"]),
        ("7.12 - Binary Tree Right Side View", "Medium", ["Tree", "BFS"]),
        ("7.13 - Left View of a Binary Tree", "Medium", ["Tree", "BFS"]),
        ("7.14 - Top View of a Binary Tree", "Medium", ["Tree", "BFS"]),
        ("7.15 - Boundary Traversal of a Binary Tree", "Hard", ["Tree", "Recursion"]),
        ("7.16 - Binary Tree Zigzag Traversal", "Medium", ["Tree", "Queue"]),
        ("7.17 - Construct a Binary Tree from Preorder and Inorder Traversal", "Hard", ["Tree", "Recursion"]),
        ("7.18 - Construct a Binary Tree from Inorder and Postorder Traversal", "Hard", ["Tree", "Recursion"]),
        ("7.19 - Transform One Tree to Another", "Hard", ["Tree"]),
        ("7.20 - Symmetric Tree", "Easy", ["Tree"]),
        ("7.21 - Mirror Tree", "Easy", ["Tree"]),
        ("7.22 - Diameter of a Binary Tree", "Easy", ["Tree", "Recursion"]),
        ("7.23 - Height of a Spiral Tree", "Hard", ["Tree"]),
        ("7.24 - Search a Binary Tree", "Easy", ["Tree", "Binary Search"]),
        ("7.25 - Find a Peak in a Bitonic Array", "Medium", ["Tree", "Binary Search"]),
        ("7.26 - Diameter of a Rotated BST", "Hard", ["Tree", "Binary Search"]),
        ("7.27 - Identity of a Spiral Tree", "Hard", ["Tree"]),
        ("7.28 - Check if a Binary Tree is a Sum Tree", "Medium", ["Tree", "Recursion"]),
        ("7.29 - Check if a Binary Tree is a Complete Binary Tree", "Easy", ["Tree"]),
        ("7.30 - Check if a Binary Tree is a Full Binary Tree", "Easy", ["Tree"]),
        ("7.31 - Count Number of Nodes", "Medium", ["Tree"]),
        ("7.32 - Maximum Sum of a Path in a Binary Tree", "Medium", ["Tree", "Dynamic Programming"]),
        ("7.33 - Lowest Common Ancestor of Nodes in a Binary Tree", "Medium", ["Tree", "BFS", "DFS"]),
        ("7.34 - Two Sum in a BST", "Medium", ["Tree", "BST", "Two Pointer"]),
        ("7.35 - Kth Smallest Element in a BST", "Medium", ["Tree", "BST"]),
        ("7.36 - Inorder Successor of a Node in a BST", "Medium", ["Tree", "BST"]),
        ("7.37 - BST Inorder Traversal", "Easy", ["Tree", "BST"]),
        ("7.38 - Construct a BST from a Preorder Traversal", "Medium", ["Tree", "BST"]),
        ("7.39 - Serialize and Deserialize a Binary Tree", "Hard", ["Tree", "Design"]),
    ]),
    ("Step 8 - Binary Search Trees", [
        ("8.1 - Introduction to BST", "Easy", ["BST"]),
        ("8.2 - Search in a BST", "Easy", ["BST"]),
        ("8.3 - Find the Minimum in a BST", "Easy", ["BST"]),
        ("8.4 - Find the Maximum in a BST", "Easy", ["BST"]),
        ("8.5 - Find the Inorder Successor of a Node in a BST", "Medium", ["BST"]),
        ("8.6 - Floor in a BST", "Medium", ["BST"]),
        ("8.7 - Ceil in a BST", "Medium", ["BST"]),
        ("8.8 - Insert in a BST", "Medium", ["BST"]),
        ("8.9 - Delete a Node in a BST", "Medium", ["BST"]),
        ("8.10 - Deleting the Minimum and Maximum from a BST", "Medium", ["BST"]),
        ("8.11 - Inorder Traversal of a BST", "Easy", ["BST"]),
        ("8.12 - Preorder Traversal of a BST", "Easy", ["BST"]),
        ("8.13 - Postorder Traversal of a BST", "Easy", ["BST"]),
        ("8.14 - Build a BST from a Sorted Array", "Easy", ["BST", "Array"]),
        ("8.15 - Balance a BST", "Medium", ["BST", "Tree"]),
        ("8.16 - Merge Two Balanced BST", "Medium", ["BST"]),
        ("8.17 - Inorder Traversal of a BST in O(n) Space", "Medium", ["BST", "Stack"]),
    ]),
    ("Step 9 - Heaps / Priority Queue", [
        ("9.1 - Introduction to Priority Queues", "Easy", ["Heap"]),
        ("9.2 - Min Heap and Max Heap", "Easy", ["Heap"]),
        ("9.3 - Build a Heap from an Array", "Medium", ["Heap"]),
        ("9.4 - Insertion in a Heap", "Medium", ["Heap"]),
        ("9.5 - Delete from a Heap", "Medium", ["Heap"]),
        ("9.6 - Kth Smallest / Largest Element in an Array", "Medium", ["Heap"]),
        ("9.7 - Merge K Sorted Arrays", "Hard", ["Heap"]),
        ("9.8 - K Largest Elements", "Medium", ["Heap"]),
        ("9.9 - Book Tickets (Flight Booking)", "Medium", ["Heap"]),
        ("9.10 - Connecting the Graph", "Medium", ["Heap", "Graph"]),
    ]),
    ("Step 10 - Greedy", [
        ("10.1 - Introduction to Greedy", "Easy", ["Greedy"]),
        ("10.2 - Fractional Knapsack", "Medium", ["Greedy"]),
        ("10.3 - Non Overlapping Intervals", "Medium", ["Greedy"]),
        ("10.4 - Jump Game II", "Medium", ["Greedy"]),
        ("10.5 - Jump Game", "Medium", ["Greedy", "Dynamic Programming"]),
        ("10.6 - Gas Station", "Medium", ["Greedy"]),
        ("10.7 - Candy", "Hard", ["Greedy"]),
        ("10.8 - Maximum Number of Events That Can Be Attended", "Medium", ["Greedy", "Heap"]),
        ("10.9 - Partition Array for Maximum Subarray Sum", "Hard", ["Greedy", "Dynamic Programming"]),
        ("10.10 - Min Triplet Sum", "Medium", ["Greedy", "Sorting"]),
    ]),
    ("Step 11 - Dynamic Programming", [
        ("11.1 - Introduction to Dynamic Programming", "Easy", ["Dynamic Programming"]),
        ("11.2 - Fibonacci Numbers", "Easy", ["Dynamic Programming"]),
        ("11.3 - 0/1 Knapsack", "Medium", ["Dynamic Programming"]),
        ("11.4 - Unbounded Knapsack", "Medium", ["Dynamic Programming"]),
        ("11.5 - Coin Change", "Medium", ["Dynamic Programming"]),
        ("11.6 - Partition Equal Subset Sum", "Medium", ["Dynamic Programming"]),
        ("11.7 - N Stairs", "Medium", ["Dynamic Programming"]),
        ("11.8 - Minimum Coins", "Medium", ["Dynamic Programming"]),
        ("11.9 - 2D DP", "Medium", ["Dynamic Programming"]),
        ("11.10 - Russian Dolls", "Medium", ["Dynamic Programming"]),
        ("11.11 - Grid Unique Paths", "Medium", ["Dynamic Programming"]),
        ("11.12 - Candy", "Hard", ["Dynamic Programming"]),
        ("11.13 - Min Cost Path", "Medium", ["Dynamic Programming"]),
        ("11.14 - Binary String with Subsequences Representing 1 to N", "Hard", ["Dynamic Programming"]),
        ("11.15 - Number of Distinct Subsequences", "Medium", ["Dynamic Programming", "String"]),
        ("11.16 - Unique Paths in a Grid with Obstacles", "Medium", ["Dynamic Programming"]),
        ("11.17 - Climbing Stairs", "Easy", ["Dynamic Programming"]),
        ("11.18 - Count Ways to Reach the n'th Stair", "Medium", ["Dynamic Programming"]),
        ("11.19 - House Robber", "Medium", ["Dynamic Programming"]),
        ("11.20 - Coin Change II", "Medium", ["Dynamic Programming"]),
        ("11.21 - Sum of Non-negative Numbers", "Medium", ["Dynamic Programming"]),
        ("11.22 - Partitions with Specific Difference", "Hard", ["Dynamic Programming"]),
        ("11.23 - Longest Increasing Subsequence", "Medium", ["Dynamic Programming"]),
        ("11.24 - Building Bridges", "Hard", ["Dynamic Programming"]),
        ("11.25 - Non Repeating Subsequence", "Hard", ["Dynamic Programming", "String"]),
        ("11.26 - Number of Different Ways", "Hard", ["Dynamic Programming"]),
        ("11.27 - Tiling Problem", "Medium", ["Dynamic Programming"]),
        ("11.28 - Minimum Number of Jumps", "Hard", ["Dynamic Programming", "Greedy"]),
    ]),
    ("Step 12 - Tries", [
        ("12.1 - Insert and Search", "Medium", ["Trie"]),
        ("12.2 - Prefix Search", "Medium", ["Trie"]),
        ("12.3 - Word Search II", "Hard", ["Trie", "Backtracking", "Matrix"]),
    ]),
    ("Step 13 - Graphs", [
        ("13.1 - Introduction and BFS", "Medium", ["Graph", "BFS"]),
        ("13.2 - DFS Traversal", "Medium", ["Graph", "DFS"]),
        ("13.3 - BFS in Disconnected Graph", "Medium", ["Graph", "BFS"]),
        ("13.4 - DFS in Disconnected Graph", "Medium", ["Graph", "DFS"]),
        ("13.5 - BFS Shortest Path in an Unweighted Graph", "Medium", ["Graph", "BFS"]),
        ("13.6 - DFS in a Graph", "Medium", ["Graph", "DFS"]),
        ("13.7 - BFS in a Grid", "Medium", ["Graph", "BFS", "Matrix"]),
        ("13.8 - Rotting Oranges", "Medium", ["Graph", "BFS", "Matrix"]),
        ("13.9 - Number of Islands", "Medium", ["Graph", "BFS", "DFS", "Matrix"]),
        ("13.10 - Flood Fill", "Medium", ["Graph", "BFS", "DFS"]),
        ("13.11 - Number of Connected Components in a Graph", "Medium", ["Graph", "Union Find"]),
        ("13.12 - Bipartite Graph", "Medium", ["Graph", "BFS", "DFS"]),
        ("13.13 - A* Search Algorithm", "Hard", ["Graph"]),
        ("13.14 - Minimum Spanning Tree", "Hard", ["Graph"]),
        ("13.15 - Prim's and Kruskal's Algorithm", "Hard", ["Graph"]),
        ("13.16 - Travelling Salesman Problem", "Hard", ["Graph", "Dynamic Programming"]),
        ("13.17 - Disjoint Set", "Medium", ["Graph", "Union Find"]),
        ("13.18 - Shortest Path in a Weighted Graph", "Medium", ["Graph"]),
    ]),
    ("Step 14 - Sliding Window", [
        ("14.1 - Introduction to Sliding Window", "Medium", ["Sliding Window"]),
        ("14.2 - Maximum Sliding Window", "Hard", ["Sliding Window", "Heap"]),
        ("14.3 - Minimum Sliding Window", "Hard", ["Sliding Window", "Heap"]),
        ("14.4 - Longest Substring without Repeating Characters", "Medium", ["Sliding Window", "String"]),
        ("14.5 - Sliding Window Maximum", "Hard", ["Sliding Window", "Queue"]),
        ("14.6 - Longest Substring with Atmost K Distinct Characters", "Medium", ["Sliding Window", "String"]),
        ("14.7 - Subarray Sum Equals K", "Medium", ["Sliding Window", "Array"]),
        ("14.8 - Fruit Into Baskets", "Medium", ["Sliding Window", "Array"]),
        ("14.9 - Minimum Number of Flips to Make the Binary String Alternating", "Medium", ["Sliding Window", "String"]),
    ]),
    ("Step 15 - Binary Exponentiation", [
        ("15.1 - Introduction to Power", "Easy", ["Math"]),
        ("15.2 - Binary Exponentiation", "Easy", ["Math"]),
        ("15.3 - Modular Exponentiation", "Medium", ["Math"]),
        ("15.4 - Modular Inverse for Prime", "Medium", ["Math"]),
        ("15.5 - Count Primes", "Medium", ["Math"]),
        ("15.6 - Integer Overflow", "Medium", ["Math"]),
        ("15.7 - Power of a Number", "Medium", ["Math"]),
        ("15.8 - GCD and LCM", "Easy", ["Math"]),
    ]),
    ("Step 16 - Bit Manipulation", [
        ("16.1 - Bit Shifting", "Easy", ["Bit Manipulation"]),
        ("16.2 - Bitwise Operators", "Easy", ["Bit Manipulation"]),
        ("16.3 - Counting Set Bits", "Easy", ["Bit Manipulation"]),
        ("16.4 - Common Subsequence", "Hard", ["Bit Manipulation", "Dynamic Programming"]),
        ("16.5 - Bitwise Operators in C++", "Easy", ["Bit Manipulation"]),
    ]),
    ("Step 17 - Advanced Data Structures", [
        ("17.1 - Segment Trees", "Hard", ["Segment Tree"]),
        ("17.2 - Lazy Propagation", "Hard", ["Segment Tree"]),
        ("17.3 - Sparse Table", "Hard", ["Sparse Table"]),
        ("17.4 - Fenwick Tree", "Hard", ["Fenwick Tree"]),
        ("17.5 - Segment Tree and Fenwick Tree", "Hard", ["Segment Tree", "Fenwick Tree"]),
    ]),
]

STRIVER_OLD = [
    ("Step 1 - Arrays", [
        ("Second Largest", "Easy", ["Array"]),
        ("Missing Number in an Array", "Easy", ["Array"]),
        ("Max and Min of an Array", "Easy", ["Array"]),
        ("Product of Array Elements", "Easy", ["Array"]),
        ("Largest Element in an Array", "Easy", ["Array"]),
        ("Smallest Number", "Easy", ["Array"]),
        ("Frequency of Array Elements", "Easy", ["Array", "Hashing"]),
        ("Count of Smaller Elements", "Medium", ["Array"]),
        ("Square of a Sorted Array", "Easy", ["Array", "Two Pointer"]),
        ("Index of a Rotated Sorted Array", "Medium", ["Array", "Binary Search"]),
        ("Search in a Sorted Rotated Array", "Medium", ["Binary Search", "Array"]),
        ("Split Array - Largest Sum", "Hard", ["Array", "Binary Search"]),
        ("Kadane's Algorithm", "Medium", ["Array", "Dynamic Programming"]),
        ("Rotate Array", "Medium", ["Array", "Two Pointer"]),
        ("Remove Duplicates", "Easy", ["Array", "Two Pointer"]),
        ("Maximum and Minimum", "Easy", ["Array"]),
        ("Merge Two Sorted Arrays", "Medium", ["Array", "Two Pointer"]),
        ("Array Maximum Equal", "Medium", ["Array", "Hashing"]),
        ("Count Elements Greater Than X", "Easy", ["Array", "Binary Search"]),
        ("Replace Elements by its Index in an Array", "Easy", ["Array"]),
        ("Shifting Elements of the Array", "Easy", ["Array"]),
        ("Alternative Sorting", "Medium", ["Array", "Sorting"]),
        ("Sort an Array in Wave Form", "Medium", ["Array", "Sorting"]),
        ("Numbers smaller than a given number", "Easy", ["Array"]),
    ]),
    ("Step 2 - Strings", [
        ("Check String Is Palindrome or Not", "Easy", ["String", "Two Pointer"]),
        ("Pattern Matching", "Medium", ["String"]),
        ("Prefix and Suffix", "Easy", ["String"]),
        ("String Compression", "Medium", ["String"]),
        ("Valid Anagram", "Easy", ["String", "Hashing"]),
        ("Longest Substring without Repeating Characters", "Medium", ["Sliding Window", "String"]),
        ("Longest Palindromic Substring", "Medium", ["String", "Dynamic Programming"]),
        ("String Matching", "Hard", ["String"]),
        ("Permutation of a String", "Medium", ["Backtracking", "String"]),
        ("Remove Spaces", "Easy", ["String"]),
        ("Extract the integers from a string", "Medium", ["String"]),
        ("String Reverse", "Easy", ["String", "Two Pointer"]),
        ("Count Words", "Easy", ["String"]),
        ("Check Palindrome", "Easy", ["String", "Two Pointer"]),
        ("Case-specific Sorting of Strings", "Medium", ["String", "Sorting"]),
        ("Odd Even Character", "Easy", ["String"]),
        ("Reverse Words in a String", "Medium", ["String"]),
        ("To Lower Case", "Easy", ["String"]),
        ("Maximum occurring Character", "Easy", ["String", "Hashing"]),
    ]),
    ("Step 3 - Sorting", [
        ("Sort the array", "Medium", ["Sorting"]),
        ("Sort the Colors", "Medium", ["Sorting", "Array"]),
        ("Quick Sort", "Medium", ["Sorting", "Recursion"]),
        ("Selection Sort", "Easy", ["Sorting"]),
        ("Bubble Sort", "Easy", ["Sorting"]),
        ("Insertion Sort", "Easy", ["Sorting"]),
        ("Count Inversions", "Medium", ["Sorting", "Array"]),
        ("Merge Two Sorted Arrays", "Medium", ["Sorting", "Array"]),
    ]),
    ("Step 4 - Binary Search", [
        ("Binary Search", "Easy", ["Binary Search", "Array"]),
        ("Floor and Ceil of a Number", "Easy", ["Binary Search"]),
        ("Lower Bound", "Medium", ["Binary Search"]),
        ("Upper Bound", "Medium", ["Binary Search"]),
        ("Count Occurrences", "Medium", ["Binary Search"]),
        ("Search an Element in a Rotated Sorted Array", "Medium", ["Binary Search"]),
        ("Find a Peak Element", "Medium", ["Binary Search"]),
        ("Single Element in a Sorted Array", "Medium", ["Binary Search"]),
        ("Allocate Minimum Number of Pages", "Hard", ["Binary Search"]),
    ]),
    ("Step 5 - Linked List", [
        ("Linked List Insertion", "Easy", ["Linked List"]),
        ("Delete a Node in a Linked List", "Easy", ["Linked List"]),
        ("Count Nodes of a Linked List", "Easy", ["Linked List"]),
        ("Sum of Nodes of a Linked List", "Easy", ["Linked List"]),
        ("Reverse a Linked List", "Easy", ["Linked List"]),
        ("Detect Cycle in a Linked List", "Easy", ["Linked List", "Two Pointer"]),
        ("Data Structure", "Easy", ["Linked List"]),
        ("Delete Nth Node from the End of Linked List", "Medium", ["Linked List", "Two Pointer"]),
        ("Middle of the Linked List", "Easy", ["Linked List", "Two Pointer"]),
        ("Delete a Key from a Linked List", "Easy", ["Linked List"]),
        ("Add Two Numbers Represented as a Linked List", "Medium", ["Linked List"]),
        ("Maximum Sum of Two Numbers in a Linked List", "Medium", ["Linked List", "Two Pointer"]),
    ]),
    ("Step 6 - Trees", [
        ("Traversal", "Easy", ["Tree"]),
        ("Height of Tree", "Easy", ["Tree"]),
        ("Identical Trees", "Easy", ["Tree"]),
        ("Mirror Tree", "Easy", ["Tree"]),
        ("Sum of Nodes", "Easy", ["Tree"]),
        ("Balanced Binary Tree", "Easy", ["Tree"]),
        ("Binary Tree into a DLL", "Medium", ["Tree"]),
        ("Inorder Traversal of a DLL", "Easy", ["Linked List"]),
        ("Binary Search Tree", "Medium", ["Tree", "BST"]),
        ("Preorder Successor of a Node in a BST", "Medium", ["BST"]),
        ("Postorder Successor of a Node in a BST", "Medium", ["BST"]),
        ("Delete a Node in a BST", "Medium", ["BST"]),
        ("Count BST Nodes that lie in a given range", "Medium", ["BST"]),
        ("Serialize and Deserialize a Binary Tree", "Hard", ["Tree", "Design"]),
        ("Lowest Common Ancestor in a Binary Tree", "Medium", ["Tree"]),
    ]),
    ("Step 7 - Tries", [
        ("Construct a Trie", "Medium", ["Trie"]),
        ("Search a Word in a Trie", "Medium", ["Trie"]),
        ("Count Words in a Trie", "Medium", ["Trie"]),
        ("Find the Shortest Prefix of a Word in a Trie", "Medium", ["Trie"]),
    ]),
    ("Step 8 - Dynamic Programming", [
        ("Longest Increasing Subsequence", "Medium", ["Dynamic Programming"]),
        ("Smallest Number of Jumps", "Hard", ["Dynamic Programming"]),
        ("Ways to Climb Stairs", "Medium", ["Dynamic Programming"]),
        ("Maximum Sum Non Adjacent Elements", "Medium", ["Dynamic Programming"]),
        ("Print Longest Common Subsequence", "Hard", ["Dynamic Programming"]),
        ("Edit Distance", "Hard", ["Dynamic Programming", "String"]),
        ("Maximum Sum Rectangle", "Hard", ["Dynamic Programming"]),
        ("Partition Equal Subset Sum", "Medium", ["Dynamic Programming"]),
    ]),
    ("Step 9 - Greedy", [
        ("Fractional Knapsack", "Medium", ["Greedy"]),
        ("Interval Scheduling", "Medium", ["Greedy"]),
        ("Greedy Algorithms", "Medium", ["Greedy"]),
        ("Huffman Encoding", "Hard", ["Greedy", "Heap"]),
        ("Minimum Platforms", "Medium", ["Greedy", "Sorting"]),
    ]),
    ("Step 10 - Graphs", [
        ("BFS", "Medium", ["Graph", "BFS"]),
        ("DFS", "Medium", ["Graph", "DFS"]),
        ("Number of Islands", "Medium", ["Graph", "BFS", "DFS", "Matrix"]),
        ("MST using Kruskal's Algorithm", "Hard", ["Graph"]),
        ("MST using Prim's Algorithm", "Hard", ["Graph"]),
        ("Dijkstra's Algorithm", "Hard", ["Graph"]),
        ("Bellman Ford", "Hard", ["Graph"]),
        ("Topological Sort", "Hard", ["Graph"]),
        ("Detect a Cycle in a Graph", "Medium", ["Graph", "BFS", "DFS"]),
        ("Disjoint Set", "Medium", ["Graph", "Union Find"]),
    ]),
]

LOVE_BABBAR = [
    ("Getting Started", [
        ("Merge two sorted arrays", "Easy", ["Array", "Sorting"]),
        ("Merge k sorted arrays", "Medium", ["Heap", "Array"]),
        ("Validate parentheses", "Easy", ["Stack", "String"]),
        ("Parity of a string", "Easy", ["Bit Manipulation", "String"]),
    ]),
    ("Arrays", [
        ("Two Sum", "Easy", ["Array", "Hashing"]),
        ("Maximum and minimum of an array", "Easy", ["Array"]),
        ("Maximum and minimum of an array using three comparisons", "Easy", ["Array"]),
        ("Move all zeroes to the end", "Easy", ["Array", "Two Pointer"]),
        ("Smallest and second smallest elements", "Easy", ["Array"]),
        ("Check if two arrays are equal or not", "Easy", ["Array"]),
        ("Remove duplicates in an array", "Easy", ["Array", "Hashing"]),
        ("Maximum in a bitonic array", "Medium", ["Array", "Binary Search"]),
        ("Maximum in a bitonic array using linear time complexity", "Medium", ["Array"]),
        ("Minimize the heights", "Medium", ["Array", "Sorting"]),
        ("Minimum number of distinct elements", "Medium", ["Array", "Hashing"]),
        ("Two pointer technique", "Medium", ["Array", "Two Pointer"]),
        ("Maximum difference", "Medium", ["Array"]),
        ("Maximum Index", "Medium", ["Array"]),
        ("Next greater element", "Medium", ["Stack", "Array"]),
        ("Next smaller element", "Medium", ["Stack", "Array"]),
        ("Max sum without adjacents 2", "Medium", ["Array", "Dynamic Programming"]),
        ("Print the maximum sum of a subsequence using a greedy approach", "Medium", ["Array", "Greedy"]),
        ("Maximum non repeating characters", "Medium", ["String", "Hashing"]),
        ("Smallest range covering elements from K lists", "Hard", ["Array", "Sliding Window", "Heap"]),
        ("Count the triplets", "Medium", ["Array"]),
        ("Maximum product of an array", "Medium", ["Array"]),
        ("Maximum sum of 3 elements", "Medium", ["Array"]),
        ("Array of all permutations of N elements", "Hard", ["Backtracking"]),
        ("Target sum", "Medium", ["Backtracking", "Array"]),
        ("Maximum product of three integers", "Medium", ["Array"]),
    ]),
    ("Sorting", [
        ("Sort an array of 0s, 1s and 2s", "Medium", ["Sorting", "Array"]),
        ("Longest consecutive sequence", "Medium", ["Array", "Hashing"]),
        ("Shortest word distance", "Medium", ["Array", "String"]),
        ("K largest elements", "Medium", ["Heap", "Array"]),
        ("K closest elements", "Medium", ["Sorting", "Array"]),
    ]),
    ("Binary Search", [
        ("Binary search", "Easy", ["Binary Search", "Array"]),
        ("Minimum number of steps to reach a number", "Medium", ["Binary Search"]),
        ("Allocate minimum number of pages", "Hard", ["Binary Search"]),
        ("Painter's partition problem", "Hard", ["Binary Search"]),
        ("Gas station", "Medium", ["Binary Search"]),
        ("Search in a rotated sorted array", "Medium", ["Binary Search", "Array"]),
        ("Peak element in an array", "Medium", ["Binary Search", "Array"]),
        ("Kth element in a sorted array", "Medium", ["Binary Search"]),
    ]),
    ("Strings", [
        ("Reverse a String", "Easy", ["String", "Two Pointer"]),
        ("Check if a string is a palindrome", "Easy", ["String", "Two Pointer"]),
        ("Longest substring without repeating characters", "Medium", ["String", "Sliding Window"]),
        ("KMP algorithm", "Hard", ["String"]),
        ("Sort a string", "Easy", ["String", "Sorting"]),
    ]),
    ("Linked List", [
        ("Reverse a linked list", "Easy", ["Linked List"]),
        ("Add two numbers represented as linked lists", "Medium", ["Linked List"]),
        ("Delete a node without a key", "Medium", ["Linked List"]),
        ("Subtract two linked lists", "Medium", ["Linked List"]),
        ("Sum of two large numbers", "Medium", ["Linked List"]),
        ("Intersect two sorted linked lists", "Medium", ["Linked List", "Two Pointer"]),
        ("Merge two sorted linked lists", "Medium", ["Linked List"]),
        ("Swap nodes in a linked list without data", "Medium", ["Linked List"]),
    ]),
    ("Recursion and Backtracking", [
        ("Sudoku solver", "Hard", ["Backtracking", "Matrix"]),
        ("N-queens problem", "Hard", ["Backtracking", "Matrix"]),
        ("Word break problem", "Medium", ["Dynamic Programming", "String"]),
        ("Friends pairing problem", "Medium", ["Backtracking", "Dynamic Programming"]),
    ]),
    ("Dynamic Programming", [
        ("Climbing stairs", "Easy", ["Dynamic Programming"]),
        ("0/1 Knapsack problem", "Medium", ["Dynamic Programming"]),
        ("Coin change", "Medium", ["Dynamic Programming"]),
        ("Longest increasing subsequence", "Medium", ["Dynamic Programming"]),
        ("Longest common subsequence", "Medium", ["Dynamic Programming", "String"]),
        ("Partition equal subset sum", "Medium", ["Dynamic Programming"]),
        ("0/1 Knapsack problem in O(N) space", "Medium", ["Dynamic Programming"]),
        ("Matrix chain multiplication", "Medium", ["Dynamic Programming"]),
        ("Edit distance", "Hard", ["Dynamic Programming"]),
        ("Count number of ways to partition a set into K subsets", "Medium", ["Dynamic Programming"]),
        ("Count of subsets with given sum", "Medium", ["Dynamic Programming"]),
        ("Word break problem II", "Medium", ["Dynamic Programming", "String"]),
    ]),
    ("Tries", [
        ("Construct a trie from words", "Medium", ["Trie"]),
        ("Prefix search in a trie", "Medium", ["Trie"]),
        ("Word search II", "Hard", ["Trie", "Backtracking"]),
    ]),
    ("Stacks and Queues", [
        ("Next greater element", "Medium", ["Stack", "Array"]),
        ("Largest rectangle in histogram", "Hard", ["Stack"]),
        ("Rotating string", "Hard", ["Queue", "String"]),
        ("Min stack", "Medium", ["Stack"]),
        ("Maximum size rectangle in a matrix", "Hard", ["Stack", "Matrix"]),
    ]),
    ("Tree", [
        ("Identical trees", "Easy", ["Tree"]),
        ("Maximum depth of a binary tree", "Easy", ["Tree"]),
        ("Check if a binary tree is a BST", "Medium", ["Tree", "BST"]),
        ("LCA of a binary tree", "Medium", ["Tree"]),
        ("Construction of BST from inorder traversal", "Medium", ["Tree", "BST"]),
        ("Serialize and deserialize a binary tree", "Hard", ["Tree"]),
        ("Binary tree paths sum", "Medium", ["Tree", "Backtracking"]),
        ("Binary tree maximum path sum", "Medium", ["Tree", "Dynamic Programming"]),
    ]),
    ("Graph", [
        ("BFS traversal", "Medium", ["Graph", "BFS"]),
        ("DFS traversal", "Medium", ["Graph", "DFS"]),
        ("Number of islands", "Medium", ["Graph", "BFS", "DFS", "Matrix"]),
        ("Detect cycle in a directed graph", "Medium", ["Graph"]),
        ("Detect cycle in an undirected graph", "Medium", ["Graph"]),
        ("Disjoint set", "Medium", ["Graph", "Union Find"]),
        ("Topological sort", "Hard", ["Graph"]),
        ("Prim's algorithm", "Hard", ["Graph"]),
        ("Dijkstra's algorithm", "Hard", ["Graph"]),
    ]),
    ("Dynamic programming: advanced", [
        ("Tiling problem", "Medium", ["Dynamic Programming"]),
        ("Minimum jumps to reach the end of an array", "Hard", ["Dynamic Programming"]),
        ("Maximum sum of a path in a right number triangle", "Medium", ["Dynamic Programming"]),
        ("Unique paths III", "Medium", ["Backtracking", "Dynamic Programming"]),
        ("Minimum cost path in a grid", "Medium", ["Dynamic Programming"]),
        ("Cherry pickup", "Hard", ["Dynamic Programming"]),
        ("A frog's jump", "Hard", ["Dynamic Programming"]),
    ]),
    ("Disjoint Set", [
        ("Number of connected components", "Medium", ["Union Find", "Graph"]),
        ("Redundant connection", "Medium", ["Union Find", "Graph"]),
        ("Accounts merge", "Medium", ["Union Find", "Hashing"]),
    ]),
    ("Greedy", [
        ("Fractional knapsack", "Medium", ["Greedy"]),
        ("Huffman encoding", "Hard", ["Greedy", "Heap"]),
        ("Assign cookies", "Easy", ["Greedy"]),
        ("Maximum units on a truck", "Easy", ["Greedy", "Sorting"]),
    ]),
    ("Advanced structures", [
        ("Range minimum query", "Hard", ["Segment Tree"]),
        ("Range sum query", "Hard", ["Segment Tree"]),
        ("Updates on a range", "Hard", ["Segment Tree", "Lazy Propagation"]),
        ("Persistent segment tree", "Hard", ["Segment Tree"]),
        ("Merge sort tree", "Hard", ["Segment Tree"]),
        ("Fenwick tree (BIT)", "Hard", ["Fenwick Tree"]),
    ]),
]

SHEETS = {
    "striver_a2z": {
        "name": "Striver A2Z DSA Sheet",
        "description": (
            "A 40-step structured DSA roadmap that goes from the basics to advanced "
            "topics. This bundled copy contains the question index only: titles, "
            "difficulty and topics. Import a richer file to bring in statements and "
            "test cases."
        ),
        "source": "Striver (A2Z) - question index, bundled by this project",
        "version": "index-1.0",
        "steps": STRIVER_A2Z,
    },
    "striver_old": {
        "name": "Striver Old DSA Sheet",
        "description": (
            "The original 10-step Striver sheet. This bundled copy contains the "
            "question index only: titles, difficulty and topics."
        ),
        "source": "Striver (legacy) - question index, bundled by this project",
        "version": "index-1.0",
        "steps": STRIVER_OLD,
    },
    "love_babbar": {
        "name": "Love Babbar DSA Sheet",
        "description": (
            "The popular 450-question sheet grouped by topic. This bundled copy "
            "contains the question index only: titles, difficulty and topics."
        ),
        "source": "Love Babbar sheet - question index, bundled by this project",
        "version": "index-1.0",
        "steps": LOVE_BABBAR,
    },
}
